import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@src/layout";
import { Providers } from "@src/components";
import { signOut } from "@src/lib";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <AppLayout onLogout={async () => {
            "use server"
            await signOut({ redirectTo: "/" })
          }}>
            {children}
          </AppLayout>
        </Providers>
      </body>
    </html>
  );
}
